apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: main
      containers:
      - name: web
        image: gcr.io/stevenshipton-com/web:f15f4b9
        ports:
        - containerPort: 8080
