apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: main
      containers:
      - name: api
        image: gcr.io/stevenshipton-com/api:d833660a
        ports:
        - containerPort: 8080
