apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: main
      containers:
      - name: api
        image: eu.gcr.io/stevenshipton-com/api:63c2b80
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: database
                key: uri
        ports:
        - containerPort: 8080
